services:
  database:
    image: postgres:13.14-alpine
    ports:
      - "127.0.0.1:3301:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./database:/var/lib/postgresql/data:rw

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./vendor:/var/www/vendor
      - ./src:/var/www/src
      - ./config:/var/www/config
      - ./var:/var/www/var
    depends_on:
        - database