services:
  database:
    image: postgres:13.14-alpine
    ports:
      - "3301:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./database:/var/lib/postgresql/data:rw

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.test
    ports:
      - "8000:80"
    volumes:
      - ./vendor:/var/www/vendor
      - ./src:/var/www/src
      - ./config:/var/www/config
      - ./var:/var/www/var
      - ./tests:/var/www/tests
      - .phpunit.xml.dist:/var/www/phpunit.xml.dist
    depends_on:
      - database
